server:
  port: 8888

spring:
  application:
    name: CONFIG-NEW-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/RithikManchanda/microservices-config-server
          clone-on-start: true